# Generated by Django 4.2.7 on 2024-01-30 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Korrektur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktuellerStatus",
                    models.CharField(
                        choices=[
                            ("01", "Offen"),
                            ("02", "In Bearbeitung"),
                            ("03", "Umgesetzt"),
                            ("04", "Abgelehnt"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        default="Bitte tragen Sie hier die Beschreibung des Fehlers ein."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Korrekturen",
            },
        ),
        migrations.CreateModel(
            name="Kurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("kurzname", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Kurse",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "martrikelnummer",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("vorname", models.CharField(max_length=255)),
                ("nachname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Studenten",
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=255)),
                ("nachname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Tutoren",
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("01", "Tutor"), ("02", "Student")],
                        default="02",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("01", "Offen"),
                            ("02", "In Bearbeitung"),
                            ("03", "Umgesetzt"),
                            ("04", "Abgelehnt"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "aenderung_typ",
                    models.CharField(
                        choices=[
                            ("01", "Eröffnung"),
                            ("02", "Zuweisung"),
                            ("03", "Statusänderung"),
                            ("04", "Nachricht"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "korrektur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="korrektur_messages",
                        to="database.korrektur",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_messages",
                        to="database.student",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutor_messages",
                        to="database.tutor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.CreateModel(
            name="Kursmaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("01", "Gedrucktes Skript"),
                            ("02", "PDF Skript"),
                            ("03", "IU Learn (Web)"),
                            ("04", "IU Learn (iPhone)"),
                            ("05", "IU Learn (Android)"),
                            ("06", "Podcast"),
                            ("07", "Video"),
                            ("08", "Sonstiges/Allgemein"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "kurs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.kurs",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kursmaterialien",
                "unique_together": {("typ", "kurs")},
            },
        ),
        migrations.AddField(
            model_name="korrektur",
            name="bearbeiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.tutor",
            ),
        ),
        migrations.AddField(
            model_name="korrektur",
            name="ersteller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.student",
            ),
        ),
        migrations.AddField(
            model_name="korrektur",
            name="kurs",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.kurs",
            ),
        ),
        migrations.AddField(
            model_name="korrektur",
            name="kursmaterial",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.kursmaterial",
            ),
        ),
    ]
