# Generated by Django 4.2.7 on 2024-01-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_alter_korrektur_bearbeiter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fehlermeldung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matrikelnummer", models.CharField(max_length=100)),
                ("vorname", models.CharField(max_length=100)),
                ("nachname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("kursabkuerzung", models.CharField(max_length=100)),
                ("medium", models.CharField(max_length=100)),
                ("fehlerbeschreibung", models.TextField()),
            ],
        ),
    ]
