# Generated by Django 4.2.7 on 2024-01-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_alter_korrektur_bearbeiter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allgemeinsonstiges",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="gedrucktesskript",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="iulearnandroid",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="iulearniphone",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="iulearnweb",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="pdfskript",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="video",
            name="beschreibung",
        ),
        migrations.AddField(
            model_name="korrektur",
            name="beschreibung",
            field=models.TextField(default="Hier ist ein Fehler!"),
        ),
    ]
