# Generated by Django 4.2.7 on 2024-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_fehlermeldung"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fehlermeldung",
        ),
    ]
