# Generated by Django 4.2.7 on 2024-01-08 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "database",
            "0005_delete_fehlermeldung_korrektur_fehler_beschreibung",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="korrektur",
            name="kursmaterial",
        ),
    ]
