# Generated by Django 4.2.7 on 2024-01-11 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0009_remove_gedrucktesskript_korrektur_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="korrektur",
            options={"verbose_name_plural": "Korrekturen"},
        ),
        migrations.AlterModelOptions(
            name="kurs",
            options={"verbose_name_plural": "Kurse"},
        ),
        migrations.AlterModelOptions(
            name="kursmaterial",
            options={"verbose_name_plural": "Kursmaterialien"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "Studenten"},
        ),
        migrations.AlterModelOptions(
            name="tutor",
            options={"verbose_name_plural": "Tutoren"},
        ),
    ]
