# Generated by Django 4.2.7 on 2024-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "database",
            "0010_alter_korrektur_options_alter_kurs_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="korrektur",
            name="fehler_beschreibung",
        ),
        migrations.AddField(
            model_name="korrektur",
            name="beschreibung",
            field=models.TextField(default="Keine Beschreibung"),
        ),
    ]
